# This is a Gradle version catalog, for more information, see
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog

[versions]
kotlin = "1.7.20"
compose = "1.2.2"

[libraries]
compose-windowStyle = { module = "com.mayakapps.compose:window-styler", version = "0.3.2" }

[bundles]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }